// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbndwllwfwozwgajnynj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhibmR3bGx3ZndvendnYWpueW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjM4MDIsImV4cCI6MjA2MTQzOTgwMn0.RdRMi-Y650kkLIUompvCoOk6H9JQT3NooVzcRvyJgTM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);