// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sywbzurmgumpskqtozda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5d2J6dXJtZ3VtcHNrcXRvemRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NzEyNjksImV4cCI6MjA2MTQ0NzI2OX0.Tkz_KtV4NO4AepDh7iqW1O-vFJ9M2yTH7XACCVi3WR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);